### ISSUE TITLE
sillywalk-map.pdf looks black and white but is actually CMYK

### ISSUE THREAD

**Issue by FrankMittelbach** [cereda/sillypage#10]
The graphics in the PDF show as black and white, but in fact they are a combination of CMYK colors. This gets you into trouble if you submit somehting to a printing house with the expectation that it is printed in b/w (or in my case in b/w plus a spotcolor).
So the PDF for printing TLC3 got rejected because one page was not conforming to spec.

To avoid such problems I suggest to replace the pdf in the package by a real black and white version, e.g.,

[sillywalk-map.pdf](https://github.com/cereda/sillypage/files/10866166/sillywalk-map.pdf)

which I made with Acrobat Pro from the original.

**Comment by cereda** [comment]
Thanks so much, Frank! _(and deeply sorry for the trouble)_

 We will prepare a new release.

**Comment by FrankMittelbach** [comment]
not urgent (for me) ... I fixed it locally, but would be good for others too I guess

**Comment by u-fischer** [comment]
Perhaps we could  make a colorless version, the the steps could be coloured in the document.
