### ISSUE TITLE
Vector version

### ISSUE THREAD

**Issue by samcarter** [cereda/sillypage#3]
In case you ever decide to offer an option to include the walk as vectorised image, please find attached a couple of files you could use as starting point.

[Archive.zip](https://github.com/cereda/sillypage/files/7878174/Archive.zip)

**Comment by cereda** [comment]
Thanks a lot, @samcarter!

I think that's a great improvement! We can work on it for the next version. :1st_place_medal: 

You have commit privileges in this repo, so feel free to submit a pull report. I will try to prod @PhelypeOleinik  on this during the week. :wink:

**Comment by samcarter** [comment]
I did not make a PR because there are a couple of different approaches how one could use the vector image

- include every step as a separate .pdf
- include a 12 page .pdf like in the duckuments package
- include one pdf with the steps side by side like you do with your png

**Comment by PhelypeOleinik** [comment]
Thanks for the awesome work, @samcarter!

Regarding the approaches you mentioned:  I would only rule out the 12-page version, because it would need `pdfpages` to include a particular page (nothing against `pdfpages`: it's just that I think it's overkill for the job).  The other two are fine, I think.

**Comment by samcarter** [comment]
@PhelypeOleinik  Why do you need pdfpages to include a specific page? `\includegraphics[page=2]{silly_vector}` should include the specific page, or am I missing something?

**Comment by PhelypeOleinik** [comment]
@samcarter  I'm an idiot...  Somehow I had no idea option `page` existed (I recall having searched for something like that before, but I obviously failed).  Ignore my comment...

In this case, I think the 12 page PDF is a good option!
